apiVersion: v1
description: EventStore Replicator Helm chart
name: es-replicator
version: 0.2.4
icon: https://github.com/EventStore/EventStore/blob/db2de074fcf1d4a9b29cfa4baac560706e087386/ouro.png
home: https://replicator.eventstore.org